### ISSUE TITLE
Uit de readme kan ik niet opmaken op welke data je concept gebaseerd is

### ISSUE THREAD

**Issue by DaanKos** [joanpadolina/functional-programming#2]
Ik raad je aan om even op te sommen welke data je gebruikt, en op welke manier je deze verwerkt
Bijv.

Gebruikte data
- Landen + labels
- Aantal objecten per land
etc.

Dat houdt het overzichtelijk ;)

**Comment by joanpadolina** [comment]
Toegevoegd Thank you!
