### ISSUE TITLE
Klopt het dat je geen data fetched?

### ISSUE THREAD

**Issue by DaanKos** [joanpadolina/functional-programming#4]
Het lijkt erop dat je geen data fetched en zelf json files in het project gebruikt. Weet niet of dit uitmaakt voor de beoordeling, maar misschien kan je de data die je gebruikt ook ophalen met een fetch zodat het altijd up to date is?

**Comment by joanpadolina** [comment]
data fetch heb ik verstopt ! 
[die zit hier](https://github.com/joanpadolina/functional-programming/blob/master/src/index.js) 
ik heb toch maar besloten dit niet te gebruiken voor nu. But thanks!
