### ISSUE TITLE
De code is erg simpel, dat is goed! Maar de experimenten kunnen duidelijker.

### ISSUE THREAD

**Issue by DaanKos** [joanpadolina/functional-programming#6]
Het is goed dat je code zo simpel is! Maar het is wel lastig te volgen welke experimenten je hebt uitgevoerd en waar je bij die experimenten tegen aan liep.

De experimenten staan goed in de wiki, maar ik zie niet zo goed welke stappen je hebt genomen om bij dit eindresultaat te komen. Of ging het in een keer helemaal goed?

**Comment by joanpadolina** [comment]
Ah Ja klopt! heb het niet gedocumenteerd omdat het voor mijn gevoel te snel ging en te snel naar oplossingen aan het zoeken was. Ga ik meenemen voor de volgende keer! Thanks
