### ISSUE TITLE
Algemene feedback

### ISSUE THREAD

**Issue by DaanKos** [joanpadolina/functional-programming#7]
Veel van de punten op het peerfeedback formulier lijken aanwezig te zijn, dus je bent goed bezig.

Ik zou vooral dus focussen op het verduidelijken van het proces dat je hebt doorlopen, waarbij week 2 van het logboek erg zou helpen.

De uiteindelijke code zal erg kort zijn, dus is het goed documenteren van het proces belangrijk om te zien wat je geleerd hebt en waar je moeite mee hebt gehad.

**Comment by joanpadolina** [comment]
Ga ik doen dank u!
